name: BungeeBan
version: 2.6.4
author: VinciDev
description: A fully customizable and easy to use BungeeCord plugin managing Bans and Mutes, and much more!
website: https://github.com/vincidev/BungeeBan
main: de.vincidev.bungeeban.BungeeBan
commands:
  ban:
    permission: BungeeBan.Ban
  unban:
    permission: BungeeBan.Unban
  tempban:
    permission: BungeeBan.TempBan
  kick:
    permission: BungeeBan.Kick
  check:
    permission: BungeeBan.Check
  whitelist:
    permission: BungeeBan.Whitelist.Admin
